[profile.default]
optimizer = true
optimizer_runs = 200  # Start with 200; higher values (e.g., 1000) optimize more but compile slower
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
